"use client";

import ReactQueryProvider from "@/providers/ReactQueryProvider";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";
import { ProductProvider } from "@/contexts/ProductContext";
import { SelectedModeProvider } from "@/contexts/SelectionModeContext";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { CartProvider } from "@/contexts/CartContext";

// export const metadata: Metadata = {

//   title: "Lunga Traders",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="w-full">
      <body className="w-full">
        <ReactQueryProvider>
          <SelectedModeProvider>
            <UserProvider>
              <CartProvider>
                <ProductProvider>
                  <Navbar />
                  {children}
                  <Footer />
                </ProductProvider>
              </CartProvider>
            </UserProvider>
          </SelectedModeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
