export interface Product {
    _id: string,
    make: string,
    model: string,
    year:number,
    color:string,
    size:string,
    category: string,
    sub_category:string,
    tags?: string,
    description: string,
    original_price: number,
    sale_price: number,
    purchace_quantity: number,
    stock_quantity: number,
    user_id:string,
    buying:boolean,
    ratio_review?:number,
    number_of_reviews_done?:number,
    image_src:string,
    images_src?:string [],
}

export interface ProductInput {
    make: string,
    model: string,
    year:number,
    color:string,
    size:string,
    category: string,
    sub_category:string,
    tags?: string,
    buying:boolean,
    description: string,
    original_price: number,
    sale_price: number,
    purchace_quantity: number,
    stock_quantity: number,
    user_id:string,
    ratio_review?:number,
    number_of_reviews_done?:number,
    image_src:string,
    images_src?:string [],
}